# Generated by Django 5.1.2 on 2024-10-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_admin', '0003_feeshistory_libraryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeshistory',
            name='given_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management_admin.libraryhistory'),
        ),
    ]
